rows = 200
cols = 200
scale = 30
# octaves = 2
# persistence = 0.5
# lacunarity = 0
# seed = 6
octaves = 2
persistence = 1
lacunarity = 2.0
seed = 4
smoothness = 5
new_min = -5
new_max = 4 # Adjust the new maximum height